# Generated by Django 3.1.7 on 2023-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequest',
            name='fuel_station',
            field=models.CharField(choices=[('hp', 'indian'), ('indian', 'hp')], max_length=10),
        ),
    ]
